#### general settings
name:  # name里有debug也可以
model_type: EHDRGANModel  # 这里写你自定义的model名字,一定是在models里注册了的model
use_tb_logger: true
distortion: sr
scale: 1
# gpu_ids: [0]
num_gpu: auto
manual_seed: 0

#### datasets
datasets:
  train:
    name: Single_LDR2HDR
    type: LQGT_dataset  # 这里写你注册了的数据集的名字
    data_type: img  # img或lmdb
    # 剩下的这些参数都必须和data/对应type的dataset类需要用到的重合
    dataroot_LQ: /data0/NTIRE2021_HDR/000_Train_SingleFrame_FirstStage/medium_sub
    dataroot_GT: /data0/NTIRE2021_HDR/000_Train_SingleFrame_FirstStage/gt_sub
    dataroot_ratio: /data0/NTIRE2021_HDR/000_Train_SingleFrame_FirstStage/alignratio
    # n_workers: 8
    # batch_size: 16
    GT_size: 160
    use_flip: true
    use_rot: true
    condition: image
    # 没看到的
    # scale: 1
    # phase: train
    num_gpu: 0  # 是否有gpu
    # dist: false
    # sampler: None
    # seed : None
    # use_shuffle: true
    # num_prefetch_queue: ?
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: cpu  # cpu or cuda
  val:
    name: Single_LDR2HDR
    type: LQGT_condition
    dataroot_LQ: /data0/NTIRE2021_HDR/000_Valid_SingleFrame_FirstStage/medium
    dataroot_GT: /data0/NTIRE2021_HDR/000_Valid_SingleFrame_FirstStage/gt
    dataroot_ratio: /data0/NTIRE2021_HDR/000_Valid_SingleFrame_FirstStage/alignratio
    condition: image

#### network structures
network_G:
  which_model_G: HDRUNet
  in_nc: 3
  out_nc: 3
  nf: 64
  act_type: relu

#### path
path:
  # root: ./
  # pretrain_model_G: ../experiments/...
  # strict_load: false
  # resume_state: ../experiments/...
  # experiment root
  experiments_root: ./experiments
  # if not in_train:
  # results_root: xxx
  # log: log文件想储存在的文件夹名称

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: MultiStepLR # MultiStepLR | CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  # niter: 1000000 # 600000
  total_iter: 600000  #就是总迭代数，total epoch = total_iter / num_batch
  warmup_iter: -1  # no warm up

  # lr_scheme: MultiStepLR
  lr_steps: [200000, 400000, 600000, 800000]
  lr_gamma: 0.5

  pixel_criterion: tanh_l1 # l1 | l2 | tanh_l1 | tanh_l2
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true  # 是否使用logger
  wandb:
    project: ~
    resume_id: ~


#### 没看到的
auto_resume: false
in_train: true